# Generated by Django 5.2.8 on 2025-12-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_link',
            field=models.URLField(blank=True, help_text='Your Razorpay Payment Page or UPI Link', null=True),
        ),
    ]
