# Generated by Django 5.2.8 on 2025-12-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_profile_payment_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_link',
            field=models.URLField(blank=True, help_text='Razorpay or UPI Link', null=True),
        ),
    ]
